name: auto-reviewer-assign
on: pull_request

jobs:
  auto-reviewer-assign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          dot: true
